CFLAGS   += -w $(HTM_RETRIES) $(RETRY_POLICY)

CPPFLAGS := $(CFLAGS)
LIBS     += $(CFLAGS) -L/home/shady/lib/ -I ../../../stms/norec/ -lrt -mcpu=power8 -mtune=power8 -lm -L../../../stms/norec/ -lnorec -ltcmalloc -lpthread -L/home/shady/lib/boost/lib/ -lboost_system -lm
LDFLAGS  += $(LIBS)
